language: csharp

mono: 5.18.0
dotnet: 5.0.100

script:
  - dotnet build FParsec.sln -c $CONFIGURATION -v n
  - |
    if [ "$RUN_TESTS" == "1" ]; then
      dotnet run --no-build -p Test -c $CONFIGURATION -f $TFM
    fi

env:
  - CONFIGURATION=Release
    TFM=net45
  - CONFIGURATION=Release-LowTrust
    TFM=net45
  - CONFIGURATION=Release-LowTrust
    TFM=net5.0
    RUN_TESTS=1

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
